import type { Condition, SurveyConfig } from '../engine/types';

// שאלון אישוש הפרסונות — גרסה 1.
//
// נגזר משלד המחקר (קונפלואנס MTG 13729793) בתהליך הזיקוק המתועד ב-docs/:
//   distillation-plan.md · persona-mapping.md · question-triage.md · wording-v1.md
// מיפוי מזהה → קוד שלד → קידוד: docs/codebook.md
//
// היקף (חלופה ב׳ שאושרה): סינון 5 · A 19 · B 19 · C 12 · דמוגרפיה 7.
//
// ⚠ אינווריאנטת segment: משתני onSubmit לא מתאפסים בניווט אחורה, ולכן כל מסך שמציב
//   את segment עושה זאת בזוג כללים משלים (תנאי + not(תנאי)) — s_status מציב A או
//   'pending', ו-s_actions מציב B או C. כך חזרה אחורה ושינוי תשובה תמיד דורסת את
//   הערך הישן במקום להשאיר אותו. כל מסך עם showIf על segment יושב אחרי שני המסכים
//   האלה, ו-showIf של s_timeline/s_actions נשען על *התשובה* ל-s_status ולא על
//   המשתנה — כך שכל שינוי בתשובה מעביר את המשיב שוב דרך מסך שמחשב את segment מחדש.

/** מקטע B = צפי ≤ 12 חודשים וגם פעולה ממשית אחת לפחות ב-90 יום. */
const segmentBRule: Condition = {
  all: [
    { q: 's_timeline', op: 'in', value: ['m0_3', 'm4_6', 'm7_12'] },
    // השלד מונה את כל שבע הפעולות כ"ממשיות" — כולל חיפוש נכס, עו"ד/מתווך והכנת מסמכים.
    {
      q: 's_actions',
      op: 'includesAny',
      value: ['budget', 'bank', 'advisor', 'approval', 'search', 'legal', 'docs'],
    },
  ],
};

/** מסלול A = משכנתה פעילה או מעורבות בחמש השנים האחרונות. */
const statusIsA: Condition = { q: 's_status', op: 'in', value: ['active', 'past5'] };

const inA: Condition = { var: 'segment', op: 'eq', value: 'A' };
const inB: Condition = { var: 'segment', op: 'eq', value: 'B' };
const inC: Condition = { var: 'segment', op: 'eq', value: 'C' };

/** אפשרויות סוג העסקה — משותפות למסלול B ולמסך הגשר של A (הכרעה 7.1/7.2). */
const DEAL_TYPES = [
  { id: 'first', label: 'דירה ראשונה' },
  { id: 'upgrade', label: 'שיפור דיור — מכירת הדירה הקיימת ורכישת אחרת' },
  { id: 'investment', label: 'דירה להשקעה' },
  { id: 'build', label: 'בנייה עצמית על מגרש' },
  { id: 'share', label: 'רכישת חלק בנכס — ירושה, גירושים או שותפות' },
  { id: 'increase', label: 'הגדלת המשכנתה על נכס קיים — שיפוץ או הרחבה' },
  { id: 'other', label: 'אחר' },
];

export const questionnaire: SurveyConfig = {
  version: 'v1.0',
  randomVars: {
    // ניסוי המחיר של B39. ⚠ ערכי ברירת מחדל — טרם נגזרו ממודל עסקי.
    price: [99, 199, 349],
  },
  // תצוגה בלבד: הקונסולה מציגה את התוויות האלה במקום segment / A / B / C.
  // שמות המשתנים והערכים עצמם נשארים קוד האנליזה (docs/codebook.md).
  varMeta: {
    segment: {
      label: 'מסלול המשיב',
      values: {
        A: 'A · יש או הייתה משכנתה',
        B: 'B · לקראת משכנתה בשנה הקרובה',
        C: 'C · מוקדם מדי או לא רלוונטי',
        pending: '(טרם נקבע)',
      },
    },
    price: { label: 'מחיר בניסוי התמחור' },
  },
  screens: [
    // ─────────────────────────── בלוק 1 · הסכמה וסינון ───────────────────────────
    {
      id: 'intro',
      type: 'info',
      title: 'אנחנו חוקרים איך אנשים בישראל מתמודדים עם משכנתה',
      body: 'מטרת המחקר היא להבין כיצד אנשים בישראל נערכים למשכנתה, מקבלים החלטות ומנהלים משכנתה קיימת.\n\nהמחקר נערך עבור E.D.E.A. הוא אינו מכירה ואינו ייעוץ פיננסי, משפטי או בנקאי, והשתתפותך לא תשפיע על זכאותך לאשראי או על תנאים שתקבל/י מגוף כלשהו.\n\nאין תשובות נכונות או שגויות — אנחנו רוצים להבין מה באמת קרה ומה באמת חשוב לך.\n\nמשך השאלון: כ-10–12 דקות.',
      cta: 'להתחיל',
    },
    {
      id: 'consent',
      type: 'consent',
      title: 'הסכמה להשתתפות',
      body: 'ההשתתפות מרצון. אפשר לדלג על כל שאלה או להפסיק בכל שלב, ללא כל השלכה.\n\nנאסוף את התשובות שתמסור/י וכן נתוני שימוש טכניים מינימליים, כגון זמן השלמה וסוג מכשיר. לא נבקש מספר תעודת זהות, מספר חשבון או סיסמת בנק.\n\nהנתונים יישמרו עד תום המחקר ולא יותר מ-36 חודשים, ישמשו למחקר ולפיתוח מוצר בלבד, ויהיו נגישים לצוות המחקר של E.D.E.A ולשותפים מקצועיים המחויבים לסודיות.\n\nאם תבחר/י להשאיר פרטי קשר בסוף השאלון — הם יישמרו בנפרד מהתשובות.',
      agreeLabel: 'אני מסכים/ה להשתתף',
      declineLabel: 'לא מעוניין/ת להשתתף',
      next: [{ if: { q: 'consent', op: 'eq', value: 'declined' }, goto: 'end_screenout' }],
    },
    {
      id: 's_age',
      type: 'number',
      prompt: 'מה גילך?',
      min: 16,
      max: 120,
      integer: true,
      next: [{ if: { q: 's_age', op: 'lt', value: 18 }, goto: 'end_screenout' }],
    },
    {
      id: 's_role',
      type: 'single',
      prompt: 'מה היה, או צפוי להיות, תפקידך בהחלטה על המשכנתה?',
      options: [
        { id: 'main', label: 'מקבל/ת ההחלטה העיקרי/ת' },
        { id: 'shared', label: 'החלטה משותפת עם אדם נוסף' },
        { id: 'helper', label: 'מסייע/ת לאדם אחר בהחלטה' },
        { id: 'none', label: 'לא מעורב/ת בהחלטה' },
      ],
      next: [{ if: { q: 's_role', op: 'eq', value: 'none' }, goto: 'end_screenout' }],
    },
    {
      // מיזוג S4+S5. מנתב ל-A ומספק את הבחנת תתי-המקטעים A1/A2.
      id: 's_status',
      type: 'single',
      prompt: 'מה מתאר את מצבך בנוגע למשכנתה?',
      options: [
        {
          id: 'active',
          label: 'קיימת כיום משכנתה על דירה או נכס שבבעלותי או בבעלות משק הבית שלי',
        },
        {
          id: 'past5',
          label:
            'אין כיום משכנתה, אך הייתי מעורב/ת בנטילה, מִחזור או סגירה של משכנתה בחמש השנים האחרונות',
        },
        { id: 'none', label: 'אף אחד מהמצבים האלה' },
        { id: 'dontknow', label: 'לא יודע/ת' },
      ],
      // זוג משלים ולא כלל יחיד: בלי הענף השני, משיב שחזר אחורה ושינה את
      // התשובה מ"קיימת משכנתה" ל"אין לי" היה נשאר עם segment='A' עד
      // ש-s_actions היה מציב מחדש. 'pending' מציין "טרם נקבע" — אף showIf
      // אינו משווה אליו, ולכן שום מסך מקטע לא נפתח בטעות.
      onSubmit: [
        { var: 'segment', value: 'A', if: statusIsA },
        { var: 'segment', value: 'pending', if: { not: statusIsA } },
      ],
    },
    {
      id: 's_timeline',
      type: 'single',
      showIf: { q: 's_status', op: 'in', value: ['none', 'dontknow'] },
      prompt: 'מתי, להערכתך, תבקש/י משכנתה לצורך רכישה או בנייה?',
      options: [
        { id: 'm0_3', label: 'בתוך 0–3 חודשים' },
        { id: 'm4_6', label: 'בתוך 4–6 חודשים' },
        { id: 'm7_12', label: 'בתוך 7–12 חודשים' },
        { id: 'm13_24', label: 'בעוד שנה עד שנתיים' },
        { id: 'later', label: 'בעוד יותר משנתיים' },
        { id: 'unknown', label: 'לא יודע/ת' },
        { id: 'never', label: 'לא מתכנן/ת' },
      ],
    },
    {
      id: 's_actions',
      type: 'multi',
      showIf: { q: 's_status', op: 'in', value: ['none', 'dontknow'] },
      prompt: 'אילו מהפעולות הבאות ביצעת ב-90 הימים האחרונים?',
      options: [
        { id: 'budget', label: 'חישוב תקציב או בירור הון עצמי' },
        { id: 'bank', label: 'פגישה או שיחה עם בנק' },
        { id: 'advisor', label: 'פנייה ליועץ משכנתאות' },
        { id: 'approval', label: 'בקשת אישור עקרוני' },
        { id: 'search', label: 'חיפוש נכס פעיל' },
        { id: 'legal', label: 'שיחה עם עורך דין או מתווך' },
        { id: 'docs', label: 'הכנת מסמכים' },
        { id: 'none', label: 'לא ביצעתי אף אחת מהפעולות', exclusive: true },
      ],
      onSubmit: [
        { var: 'segment', value: 'B', if: segmentBRule },
        { var: 'segment', value: 'C', if: { not: segmentBRule } },
      ],
    },

    // ───────────────────────────── בלוק 2 · מסלול A ─────────────────────────────
    {
      id: 'a_last_when',
      type: 'single',
      showIf: inA,
      prompt: 'מתי בפעם האחרונה בדקת את המשכנתה, דיברת עליה עם איש מקצוע, או שקלת לשנות אותה?',
      help: 'השאלות הבאות עוסקות במשכנתה האחרונה שבה היית מעורב/ת. כשנכתוב "המשכנתה", נתייחס למשכנתה זו.',
      options: [
        { id: 'last_month', label: 'בחודש האחרון' },
        { id: 'm1_3', label: 'לפני 1–3 חודשים' },
        { id: 'm4_12', label: 'לפני 4–12 חודשים' },
        { id: 'over_year', label: 'לפני יותר משנה' },
        { id: 'never', label: 'לא עשיתי דבר מאלה' },
      ],
    },
    {
      id: 'a_last_why',
      type: 'text',
      showIf: { all: [inA, { q: 'a_last_when', op: 'ne', value: 'never' }] },
      prompt: 'מה גרם לך לעשות זאת דווקא אז?',
      multiline: true,
      optional: true,
      placeholder: 'לדוגמה: ראיתי שההחזר עלה · שמעתי מחבר · קיבלתי פנייה מהבנק',
    },
    {
      id: 'a_actions',
      type: 'multi',
      showIf: { all: [inA, { q: 'a_last_when', op: 'ne', value: 'never' }] },
      prompt: 'אילו פעולות ביצעת אז?',
      options: [
        { id: 'balance', label: 'בדיקת יתרה או מצב ההלוואה' },
        { id: 'report', label: 'עיון בדוח או במסמכי המשכנתה' },
        { id: 'calc', label: 'שימוש במחשבון' },
        { id: 'bank_talk', label: 'שיחה עם הבנק שלי' },
        { id: 'other_bank', label: 'בדיקה מול בנק אחר' },
        { id: 'advisor', label: 'פנייה ליועץ משכנתאות' },
        { id: 'refi', label: 'ביצוע מִחזור' },
        { id: 'partial', label: 'פירעון חלקי' },
        { id: 'postpone', label: 'החלטתי לדחות את הטיפול' },
        { id: 'none', label: 'לא ביצעתי אף פעולה', exclusive: true },
      ],
    },
    {
      id: 'a_paid',
      type: 'single',
      showIf: { all: [inA, { q: 'a_last_when', op: 'ne', value: 'never' }] },
      prompt: 'באותו אירוע, האם שילמת לגורם כלשהו כדי לקבל עזרה?',
      options: [
        { id: 'no', label: 'לא שילמתי' },
        { id: 'upto500', label: 'כן, עד 500 ש"ח' },
        { id: 'r500_2000', label: 'כן, 501–2,000 ש"ח' },
        { id: 'over2000', label: 'כן, מעל 2,000 ש"ח' },
        { id: 'dontremember', label: 'לא זוכר/ת' },
        { id: 'prefer', label: 'מעדיף/ה לא להשיב' },
      ],
    },
    {
      id: 'a_difficulty',
      type: 'matrix',
      showIf: inA,
      prompt: 'עד כמה היה לך קשה לבצע כל אחת מהפעולות הבאות?',
      items: [
        { id: 'tracks', label: 'להבין את המסלולים שמהם מורכבת המשכנתה' },
        { id: 'total_cost', label: 'להבין את העלות הכוללת' },
        { id: 'compare', label: 'להשוות בין חלופות' },
        { id: 'rate_change', label: 'להעריך כיצד שינוי בריבית או במדד ישפיע עליי' },
        { id: 'docs', label: 'לרכז את המסמכים הנדרשים' },
      ],
      scaleMin: 1,
      scaleMax: 5,
      minLabel: 'קל מאוד',
      maxLabel: 'קשה מאוד',
      naLabel: 'לא רלוונטי',
      shuffleItems: true,
    },
    {
      id: 'a_refi',
      type: 'single',
      showIf: inA,
      prompt: 'האם שקלת מִחזור של המשכנתה בשנתיים האחרונות?',
      options: [
        { id: 'considered_done', label: 'כן, ואף ביצעתי' },
        { id: 'considered_not', label: 'כן, אך לא ביצעתי' },
        { id: 'no', label: 'לא שקלתי' },
        { id: 'dontknow', label: 'לא יודע/ת' },
      ],
    },
    {
      id: 'a_refi_trigger',
      type: 'single',
      showIf: {
        all: [inA, { q: 'a_refi', op: 'in', value: ['considered_done', 'considered_not'] }],
      },
      prompt: 'מה היה הגורם הראשון שגרם לך לשקול מִחזור?',
      options: [
        { id: 'rate', label: 'שינוי בריבית במשק' },
        { id: 'payment_up', label: 'עליית ההחזר החודשי' },
        { id: 'income_down', label: 'ירידה בהכנסה' },
        { id: 'family', label: 'שינוי במצב המשפחתי' },
        { id: 'cash', label: 'סכום כסף פנוי שהתפנה' },
        { id: 'advisor_pitch', label: 'פנייה מיועץ או מגורם מקצועי' },
        { id: 'ad', label: 'פרסום או תוכן שראיתי' },
        { id: 'other', label: 'אחר' },
      ],
    },
    {
      id: 'a_refi_blocker',
      type: 'multi',
      showIf: { all: [inA, { q: 'a_refi', op: 'eq', value: 'considered_not' }] },
      prompt: 'מה עצר אותך מלבצע מִחזור?',
      maxSelections: 3,
      options: [
        { id: 'unclear_saving', label: 'לא היה ברור לי אם באמת אחסוך' },
        { id: 'fees', label: 'עמלות או עלויות נלוות' },
        { id: 'complex', label: 'התהליך נראה מסובך מדי' },
        { id: 'time', label: 'לא היה לי זמן' },
        { id: 'trust', label: 'לא סמכתי על מי שהציע' },
        { id: 'postponed', label: 'דחיתי ולא חזרתי לזה' },
        { id: 'partner', label: 'בן/בת הזוג לא היה/הייתה בעד' },
        { id: 'rejected', label: 'הבנק לא אישר' },
        { id: 'other', label: 'אחר' },
      ],
    },
    {
      id: 'a_cashflow',
      type: 'single',
      showIf: inA,
      prompt:
        'ב-12 החודשים האחרונים, באיזו תדירות שינית או צמצמת הוצאות אחרות כדי לעמוד בהחזר המשכנתה?',
      help: 'אנשים רבים נדרשים לצמצם הוצאות אחרות מעת לעת.',
      options: [
        { id: 'never', label: 'אף פעם' },
        { id: 'once', label: 'פעם אחת' },
        { id: 'few', label: '2–3 פעמים' },
        { id: 'many', label: '4–6 פעמים' },
        { id: 'most', label: 'כמעט בכל חודש' },
        { id: 'prefer', label: 'מעדיף/ה לא להשיב' },
      ],
    },
    {
      id: 'a_priority',
      type: 'single',
      showIf: inA,
      prompt: 'מה חשוב לך יותר כרגע במשכנתה שלך?',
      options: [
        { id: 'lower_monthly', label: 'להקטין את ההחזר החודשי' },
        { id: 'lower_total', label: 'להקטין את העלות הכוללת' },
        { id: 'stability', label: 'יציבות וודאות בתשלום' },
        { id: 'flexibility', label: 'גמישות לפירעון מוקדם' },
        { id: 'dontknow', label: 'לא יודע/ת' },
      ],
    },
    {
      // מסך גשר — הכרעה 7.1: מזהה פרסונות עם עסקה עתידית שנותבו ל-A.
      id: 'a_deal_soon',
      type: 'single',
      showIf: inA,
      prompt:
        'האם צפויה לך עסקת נדל"ן חדשה ב-12 החודשים הקרובים — רכישה, מכירה, בנייה או הגדלת משכנתה?',
      options: [
        { id: 'yes', label: 'כן' },
        { id: 'maybe', label: 'אולי' },
        { id: 'no', label: 'לא' },
      ],
    },
    {
      id: 'a_deal_type',
      type: 'single',
      showIf: { all: [inA, { q: 'a_deal_soon', op: 'in', value: ['yes', 'maybe'] }] },
      prompt: 'מהי העסקה?',
      // כמו B, פרט ל"דירה ראשונה" (לא רלוונטית למי שכבר במסלול A) ובתוספת דירה נוספת למגורים.
      options: [
        ...DEAL_TYPES.filter((o) => o.id !== 'first' && o.id !== 'other'),
        { id: 'additional', label: 'רכישת דירה נוספת למגורים' },
        { id: 'other', label: 'אחר' },
      ],
    },
    {
      id: 'a_advisor',
      type: 'single',
      showIf: inA,
      prompt: 'האם נעזרת ביועץ משכנתאות כאשר לקחת או שינית את המשכנתה?',
      options: [
        { id: 'private', label: 'כן, ביועץ פרטי מטעמי' },
        { id: 'bank_rep', label: 'רק בגורם מטעם הבנק' },
        { id: 'third_party', label: 'כן, בגורם מטעם קבלן, מתווך או גוף אשראי' },
        { id: 'no', label: 'לא נעזרתי באיש מקצוע' },
      ],
    },
    {
      id: 'a_advisor_checks',
      type: 'multi',
      showIf: { all: [inA, { q: 'a_advisor', op: 'ne', value: 'no' }] },
      prompt: 'אילו מהדברים הבאים עשית בעצמך — לפני שבחרת ביועץ, או במקביל לעבודה איתו?',
      options: [
        { id: 'compared', label: 'השוויתי בין כמה יועצים לפני שבחרתי' },
        { id: 'credentials', label: 'בדקתי הכשרה, ניסיון או המלצות' },
        { id: 'conflict', label: 'ביררתי כיצד הוא מתוגמל או אם יש ניגוד עניינים' },
        { id: 'verified', label: 'אימתתי בעצמי את ההצעות מול הבנקים' },
        { id: 'own_calc', label: 'עשיתי חישוב עצמאי משלי' },
        { id: 'read_docs', label: 'קראתי את המסמכים במלואם' },
        { id: 'none', label: 'לא עשיתי דבר מאלה', exclusive: true },
      ],
    },
    {
      id: 'a_no_advisor',
      type: 'multi',
      showIf: { all: [inA, { q: 'a_advisor', op: 'eq', value: 'no' }] },
      prompt: 'מדוע לא נעזרת ביועץ משכנתאות?',
      options: [
        { id: 'price', label: 'המחיר' },
        { id: 'no_need', label: 'לא ראיתי בכך צורך' },
        { id: 'trust', label: 'לא סמכתי על יועצים' },
        { id: 'control', label: 'רציתי לשמור על שליטה בתהליך' },
        { id: 'bank_enough', label: 'הבנק סיפק לי את מה שהייתי צריך' },
        { id: 'family', label: 'נעזרתי במשפחה או בחבר' },
        { id: 'unknown', label: 'לא ידעתי שקיימת אפשרות כזו' },
        { id: 'other', label: 'אחר' },
      ],
    },
    {
      id: 'a_easier',
      type: 'multi',
      showIf: inA,
      prompt:
        'לפני שנציג פתרון כלשהו — אילו שתי פעולות הקשורות למשכנתה היית הכי רוצה שיהיו קלות יותר?',
      maxSelections: 2,
      shuffleOptions: true,
      options: [
        { id: 'understand', label: 'להבין מה יש לי כיום במשכנתה' },
        { id: 'track', label: 'לעקוב אחרי שינויים לאורך זמן' },
        { id: 'compare', label: 'להשוות הצעות בין בנקים' },
        { id: 'simulate', label: 'לדעת מראש איך שינוי ישפיע עליי' },
        { id: 'docs', label: 'לרכז ולנהל מסמכים' },
        { id: 'refi', label: 'לבדוק אם כדאי למחזר' },
        { id: 'talk_bank', label: 'לנהל את השיחה מול הבנק' },
        { id: 'advisor_work', label: 'לעבוד מול יועץ בצורה מסודרת' },
      ],
    },
    {
      id: 'a_concept',
      type: 'info',
      showIf: inA,
      title: 'לפני שנמשיך — על מה אנחנו עובדים',
      body: 'אנחנו בוחנים כלי שמאפשר לראות את המשכנתה הקיימת במקום אחד, להשוות חלופות ולהבין כיצד שינויים עשויים להשפיע עליה — על בסיס נתונים שהמשתמש מזין או מחבר.\n\nהכלי אינו מחליף את ההחלטה שלך, אינו נותן ייעוץ ואינו מבטיח חיסכון.',
      cta: 'הבנתי, נמשיך',
    },
    {
      id: 'a_capabilities',
      type: 'multi',
      showIf: inA,
      prompt: 'אילו שתי יכולות היו בעלות הערך הגבוה ביותר עבורך?',
      maxSelections: 2,
      shuffleOptions: true,
      options: [
        { id: 'refi_check', label: 'בדיקה אם כדאי למחזר' },
        { id: 'monitor', label: 'ניטור שוטף והתראות על שינויים' },
        { id: 'explain', label: 'הסברים פשוטים על המשכנתה שלי' },
        { id: 'forecast', label: 'תחזית והשוואת תרחישים' },
        { id: 'docs', label: 'ניהול המסמכים' },
        { id: 'compare', label: 'השוואה בין הצעות בנקים' },
        { id: 'advisor_tools', label: 'עבודה מסודרת מול יועץ' },
      ],
    },
    {
      id: 'a_data',
      type: 'multi',
      showIf: inA,
      prompt: 'אילו מהנתונים הבאים היית מוכן/ה לשתף כדי לקבל את התוצאה הזו?',
      options: [
        { id: 'manual', label: 'נתונים שאזין ידנית' },
        { id: 'mortgage_report', label: 'דוח משכנתה מהבנק' },
        { id: 'approval', label: 'אישור עקרוני' },
        { id: 'account', label: 'נתוני חשבון הבנק' },
        { id: 'credit', label: 'נתוני אשראי' },
        { id: 'none', label: 'לא הייתי משתף/ת נתונים', exclusive: true },
      ],
    },
    {
      id: 'a_commit',
      type: 'single',
      showIf: inA,
      prompt: 'מהי הפעולה הממשית ביותר שהיית מוכן/ה לבצע בשבוע הקרוב?',
      options: [
        { id: 'read', label: 'לקרוא מידע או מדריך' },
        { id: 'enter', label: 'להזין את נתוני המשכנתה שלי' },
        { id: 'call', label: 'לקבוע שיחה של 20 דקות' },
        { id: 'upload', label: 'להעלות מסמך מושחר' },
        { id: 'pay', label: 'לשלם עבור בדיקה' },
        { id: 'none', label: 'אף אחת מהפעולות' },
      ],
      next: [{ goto: 'd_gender' }],
    },

    // ───────────────────────────── בלוק 3 · מסלול B ─────────────────────────────
    {
      id: 'b_deal_type',
      type: 'single',
      showIf: inB,
      prompt: 'מהי העסקה שבגללה את/ה מעריך/ה שתבקש/י משכנתה?',
      help: 'השאלות הבאות מתייחסות לרכישה או לפרויקט שבגללם את/ה מעריך/ה שתבקש/י משכנתה.',
      options: DEAL_TYPES,
    },
    {
      id: 'b_stage',
      type: 'single',
      showIf: inB,
      prompt: 'באיזה שלב את/ה כיום?',
      options: [
        { id: 'budget', label: 'בירור תקציב והון עצמי' },
        { id: 'search', label: 'חיפוש נכס' },
        { id: 'found', label: 'נכס נמצא' },
        { id: 'negotiation', label: 'משא ומתן' },
        { id: 'contract', label: 'לקראת חוזה או אחריו' },
        { id: 'approval', label: 'בקשת אישור עקרוני' },
        { id: 'offers', label: 'השוואת הצעות משכנתה' },
        { id: 'signing', label: 'לקראת חתימה על המשכנתה' },
      ],
    },
    {
      id: 'b_last_action',
      type: 'text',
      showIf: inB,
      prompt: 'מה הייתה הפעולה האחרונה שביצעת בנושא, מתי היא קרתה, ומה גרם לך לעשות אותה דווקא אז?',
      multiline: true,
      optional: true,
      placeholder: 'לדוגמה: לפני שבועיים נפגשנו עם הבנק, אחרי שמצאנו דירה שאהבנו',
    },
    {
      id: 'b_paid',
      type: 'single',
      showIf: inB,
      prompt: 'האם שילמת כבר עבור עזרה הקשורה לרכישה או למימון?',
      options: [
        { id: 'no', label: 'לא שילמתי' },
        { id: 'upto500', label: 'כן, עד 500 ש"ח' },
        { id: 'r500_2000', label: 'כן, 501–2,000 ש"ח' },
        { id: 'over2000', label: 'כן, מעל 2,000 ש"ח' },
        { id: 'prefer', label: 'מעדיף/ה לא להשיב' },
      ],
    },
    {
      // מיזוג B9+B10: קיום התקרה ואופן גזירתה במסך אחד.
      id: 'b_ceiling',
      type: 'single',
      showIf: inB,
      prompt: 'האם הגדרת לעצמך החזר חודשי מרבי, וכיצד הגעת אליו?',
      options: [
        { id: 'none', label: 'לא הגדרתי תקרה' },
        { id: 'budget', label: 'כן — לפי תקציב מפורט שעשיתי' },
        { id: 'rule', label: 'כן — לפי כלל אצבע או תחושה' },
        { id: 'bank', label: 'כן — לפי מה שהבנק אמר' },
        { id: 'advisor', label: 'כן — לפי מה שיועץ אמר' },
        { id: 'partner', label: 'כן — בהתייעצות עם בן/בת הזוג' },
      ],
    },
    {
      id: 'b_equity',
      type: 'multi',
      showIf: inB,
      prompt: 'מהו מקור ההון העצמי הצפוי?',
      options: [
        { id: 'savings', label: 'חיסכון עצמי' },
        { id: 'family', label: 'עזרה או מתנה מהמשפחה' },
        { id: 'family_loan', label: 'הלוואה מהמשפחה' },
        { id: 'sale', label: 'מכירת נכס קיים' },
        { id: 'investments', label: 'מימוש השקעות' },
        { id: 'loan', label: 'הלוואה נוספת' },
        { id: 'grant', label: 'מענק או זכאות' },
        { id: 'other', label: 'אחר' },
        { id: 'unknown', label: 'עדיין לא יודע/ת', exclusive: true },
      ],
    },
    {
      id: 'b_unclear',
      type: 'multi',
      showIf: inB,
      prompt: 'איזה חלק בתהליך אינו ברור לך כרגע?',
      maxSelections: 3,
      shuffleOptions: true,
      options: [
        { id: 'amount', label: 'איזה סכום נכון לקחת' },
        { id: 'monthly', label: 'מה יהיה ההחזר החודשי' },
        { id: 'tracks', label: 'מהם המסלולים ואיך בונים תמהיל' },
        { id: 'rates', label: 'ריביות והצמדות' },
        { id: 'risks', label: 'מהם הסיכונים' },
        { id: 'docs', label: 'אילו מסמכים נדרשים' },
        { id: 'banks', label: 'איך משווים בין בנקים' },
        { id: 'advisor', label: 'האם צריך יועץ ואיך בוחרים' },
        { id: 'property', label: 'איך המימון מתחבר לעסקה עצמה' },
        { id: 'clear', label: 'הכול ברור לי', exclusive: true },
      ],
    },
    {
      id: 'b_difficulty',
      type: 'matrix',
      showIf: inB,
      prompt: 'עד כמה קשה לך כרגע לבצע כל אחת מהפעולות הבאות?',
      items: [
        { id: 'docs', label: 'לרכז את המסמכים הנדרשים' },
        { id: 'amount', label: 'להחליט על הסכום' },
        { id: 'risk', label: 'להבין את הסיכון' },
        { id: 'compare', label: 'להשוות בין הצעות' },
        { id: 'coordinate', label: 'לתאם עם בן/בת הזוג או עם שותפים להחלטה' },
      ],
      scaleMin: 1,
      scaleMax: 5,
      minLabel: 'קל מאוד',
      maxLabel: 'קשה מאוד',
      naLabel: 'לא רלוונטי',
      shuffleItems: true,
    },
    {
      // מיזוג B19–B22 (SURE) למסך אחד. כל פריט מסומן = 1; הציון הוא מספר הפריטים.
      id: 'b_sure',
      type: 'multi',
      showIf: inB,
      prompt: 'אילו מהמשפטים הבאים נכונים לגביך כרגע?',
      options: [
        { id: 'certain', label: 'אני מרגיש/ה בטוח/ה מהי הבחירה הטובה עבורי' },
        { id: 'informed', label: 'ברור לי מה היתרונות והסיכונים של החלופות' },
        { id: 'values', label: 'ברור לי אילו יתרונות וסיכונים חשובים לי ביותר' },
        { id: 'support', label: 'יש לי מספיק תמיכה ועצה כדי לבחור' },
        { id: 'none', label: 'אף אחד מהמשפטים אינו נכון לגביי', exclusive: true },
      ],
    },
    {
      id: 'b_who',
      type: 'multi',
      showIf: inB,
      prompt: 'מי משתתף בהחלטה?',
      options: [
        { id: 'alone', label: 'רק אני', exclusive: true },
        { id: 'partner', label: 'בן/בת הזוג' },
        { id: 'family', label: 'הורים או בני משפחה' },
        { id: 'advisor', label: 'יועץ משכנתאות' },
        { id: 'bank', label: 'נציג הבנק' },
        { id: 'lawyer', label: 'עורך דין' },
        { id: 'agent', label: 'מתווך' },
        { id: 'other', label: 'אחר' },
      ],
    },
    {
      id: 'b_advisor',
      type: 'single',
      showIf: inB,
      prompt: 'האם פנית, או בכוונתך לפנות, ליועץ משכנתאות?',
      options: [
        { id: 'already', label: 'כבר פניתי' },
        { id: 'intend', label: 'בכוונתי לפנות' },
        { id: 'considering', label: 'שוקל/ת' },
        { id: 'no', label: 'לא מתכוון/ת' },
      ],
    },
    {
      id: 'b_next_event',
      type: 'single',
      showIf: inB,
      prompt: 'איזה אירוע יגרום לך לעבור מהשלב הנוכחי לשלב הבא?',
      options: [
        { id: 'property', label: 'מציאת נכס מתאים' },
        { id: 'equity', label: 'השלמת ההון העצמי' },
        { id: 'income', label: 'שינוי בהכנסה או ביציבות התעסוקתית' },
        { id: 'approval', label: 'קבלת אישור עקרוני' },
        { id: 'partner', label: 'הסכמה עם בן/בת הזוג' },
        { id: 'rates', label: 'שינוי בריבית' },
        { id: 'contract', label: 'מועד בחוזה או בעסקה' },
        { id: 'unknown', label: 'לא יודע/ת' },
      ],
    },
    {
      id: 'b_delay',
      type: 'single',
      showIf: inB,
      prompt: 'מה הדבר העיקרי שעלול לעכב אותך?',
      options: [
        { id: 'equity', label: 'חוסר בהון עצמי' },
        { id: 'income', label: 'הכנסה או יציבות תעסוקתית' },
        { id: 'foreign', label: 'הכנסה או מסמכים מחו"ל' },
        { id: 'docs', label: 'ריכוז המסמכים' },
        { id: 'property', label: 'לא נמצא נכס מתאים' },
        { id: 'prices', label: 'מחירי הנכסים' },
        { id: 'knowledge', label: 'חוסר ידע או ביטחון בהחלטה' },
        { id: 'partner', label: 'תיאום עם בן/בת הזוג או עם צד שלישי' },
        // חור 3 במיפוי הפרסונות — P2 (78/79), P10 (44), P12 (48/51)
        { id: 'long_commitment', label: 'חשש מהתחייבות ארוכת טווח בגיל שלי' },
        { id: 'nothing', label: 'שום דבר — התהליך מתקדם' },
        { id: 'other', label: 'אחר' },
      ],
    },
    {
      id: 'b_confident',
      type: 'multi',
      showIf: inB,
      prompt: 'לפני שנציג פתרון כלשהו — אילו שתי פעולות היית רוצה לבצע בביטחון רב יותר?',
      maxSelections: 2,
      shuffleOptions: true,
      options: [
        { id: 'budget', label: 'לקבוע כמה נכון לי לקחת' },
        { id: 'compare', label: 'להשוות בין הצעות של בנקים' },
        { id: 'tracks', label: 'לבחור תמהיל ומסלולים' },
        { id: 'risk', label: 'להבין מה קורה אם משהו משתנה' },
        { id: 'docs', label: 'לרכז ולהגיש מסמכים' },
        { id: 'negotiate', label: 'לנהל משא ומתן מול הבנק' },
        { id: 'advisor', label: 'לבחור יועץ ולעבוד מולו' },
        { id: 'timing', label: 'לתזמן נכון בין העסקה למימון' },
      ],
    },
    {
      id: 'b_concept',
      type: 'info',
      showIf: inB,
      title: 'לפני שנמשיך — על מה אנחנו עובדים',
      body: 'אנחנו בוחנים כלי שמלווה את התהליך לקראת משכנתה: מרכז את הנתונים, מציג חלופות ומסביר מה ההבדל ביניהן, ועוזר להתכונן לשיחה מול הבנק.\n\nהכלי אינו מחליף את ההחלטה שלך, אינו נותן ייעוץ ואינו מבטיח תנאים כלשהם.',
      cta: 'הבנתי, נמשיך',
    },
    {
      id: 'b_capabilities',
      type: 'multi',
      showIf: inB,
      prompt: 'אילו שתי יכולות היית בוחר/ת?',
      maxSelections: 2,
      shuffleOptions: true,
      options: [
        { id: 'budget_calc', label: 'חישוב כמה נכון לי לקחת' },
        { id: 'compare', label: 'השוואה בין הצעות בנקים' },
        { id: 'simulate', label: 'סימולציה של תרחישים' },
        { id: 'explain', label: 'הסברים פשוטים על המסלולים' },
        { id: 'docs', label: 'ניהול המסמכים והתהליך' },
        { id: 'checklist', label: 'רשימת מה צריך לעשות ומתי' },
        { id: 'advisor_tools', label: 'עבודה מסודרת מול יועץ' },
      ],
    },
    {
      id: 'b_data',
      type: 'multi',
      showIf: inB,
      prompt: 'אילו מהנתונים הבאים היית מוכן/ה להזין או לשתף?',
      options: [
        { id: 'manual', label: 'נתונים שאזין ידנית' },
        { id: 'payslips', label: 'תלושי שכר או אישורי הכנסה' },
        { id: 'approval', label: 'אישור עקרוני' },
        { id: 'account', label: 'נתוני חשבון הבנק' },
        { id: 'credit', label: 'נתוני אשראי' },
        { id: 'none', label: 'לא הייתי משתף/ת נתונים', exclusive: true },
      ],
    },
    {
      id: 'b_commit',
      type: 'single',
      showIf: inB,
      prompt: 'איזו פעולה תהיה מוכן/ה לבצע כעת?',
      options: [
        { id: 'read', label: 'לקרוא מידע או מדריך' },
        { id: 'simulate', label: 'להזין נתונים ולהריץ סימולציה' },
        { id: 'waitlist', label: 'להירשם לרשימת המתנה' },
        { id: 'call', label: 'לקבוע שיחה של 20 דקות' },
        { id: 'upload', label: 'להעלות מסמך מושחר' },
        { id: 'deposit', label: 'להפקיד פיקדון בר-החזר' },
        { id: 'none', label: 'אף אחת מהפעולות' },
      ],
    },
    {
      id: 'b_price',
      type: 'single',
      showIf: inB,
      prompt: 'אם הכלי היה עולה {price} ש"ח בתשלום חד-פעמי, מה היית עושה?',
      options: [
        { id: 'buy', label: 'קונה' },
        { id: 'check_alt', label: 'בודק/ת חלופה אחרת קודם' },
        { id: 'advisor', label: 'מעדיף/ה לשלם ליועץ במקום' },
        { id: 'no', label: 'לא קונה' },
        { id: 'dontknow', label: 'לא יודע/ת' },
      ],
    },
    {
      id: 'b_price_why',
      type: 'text',
      showIf: inB,
      prompt: 'מה הסיבה העיקרית לתשובתך?',
      multiline: true,
      optional: true,
      next: [{ goto: 'd_gender' }],
    },

    // ───────────────────────────── בלוק 4 · מסלול C ─────────────────────────────
    {
      id: 'c_housing',
      type: 'single',
      showIf: inC,
      prompt: 'מה מתאר בצורה הטובה ביותר את מצב הדיור שלך כיום?',
      help: 'אין הנחה שאת/ה אמור/ה לקחת משכנתה. אנחנו רוצים להבין כיצד הנושא משתלב, אם בכלל, בתוכניות שלך.',
      options: [
        { id: 'rent', label: 'שוכר/ת' },
        { id: 'family', label: 'גר/ה עם משפחה' },
        { id: 'owner_free', label: 'בעל/ת נכס ללא משכנתה' },
        { id: 'other', label: 'דיור אחר' },
      ],
    },
    {
      id: 'c_goal',
      type: 'single',
      showIf: inC,
      prompt: 'האם רכישת דירה היא מטרה עבורך?',
      options: [
        { id: 'yes_soon', label: 'כן, בשנים הקרובות' },
        { id: 'maybe', label: 'אולי, אין לי מועד' },
        { id: 'not_now', label: 'לא כרגע' },
        { id: 'no', label: 'לא, זו אינה מטרה שלי' },
      ],
    },
    {
      id: 'c_financial_goal',
      type: 'single',
      showIf: inC,
      prompt: 'מהי המטרה הפיננסית המרכזית שאת/ה עובד/ת עליה כרגע?',
      options: [
        { id: 'housing', label: 'דיור — חיסכון לדירה' },
        { id: 'savings', label: 'חיסכון כללי או קרן חירום' },
        { id: 'debt', label: 'סגירת חובות או הלוואות' },
        { id: 'children', label: 'הוצאות על ילדים או חינוך' },
        { id: 'business', label: 'עסק או קריירה' },
        { id: 'studies', label: 'לימודים' },
        { id: 'daily', label: 'פשוט לסגור את החודש' },
        { id: 'none', label: 'אין לי מטרה מוגדרת כרגע' },
      ],
    },
    {
      id: 'c_last_thought',
      type: 'text',
      showIf: inC,
      prompt: 'ספר/י על הפעם האחרונה שבה חשבת ברצינות על רכישת דירה. מה עורר את המחשבה ומה עשית לאחר מכן?',
      multiline: true,
      optional: true,
      placeholder: 'אפשר לדלג אם אין לך דוגמה',
    },
    {
      id: 'c_reason',
      type: 'single',
      showIf: inC,
      prompt: 'מה הסיבה העיקרית לכך שאינך קרוב/ה יותר לתהליך?',
      options: [
        { id: 'equity', label: 'אין מספיק הון עצמי' },
        { id: 'income', label: 'ההכנסה אינה מספיקה או אינה יציבה' },
        { id: 'prices', label: 'מחירי הדירות' },
        { id: 'uncertainty', label: 'אי-ודאות כללית' },
        { id: 'geography', label: 'לא ברור לי איפה ארצה לגור' },
        { id: 'prefer_rent', label: 'מעדיף/ה לשכור' },
        { id: 'knowledge', label: 'לא יודע/ת מאיפה להתחיל' },
        { id: 'other_priority', label: 'יש לי עדיפות אחרת כרגע' },
      ],
    },
    {
      id: 'c_conditions',
      type: 'multi',
      showIf: inC,
      prompt: 'אילו שני תנאים צריכים להשתנות כדי שתתחיל/י לפעול?',
      maxSelections: 2,
      shuffleOptions: true,
      options: [
        { id: 'equity', label: 'שיהיה לי הון עצמי מספיק' },
        { id: 'income', label: 'שההכנסה שלי תעלה או תתייצב' },
        { id: 'prices', label: 'שמחירי הדירות יירדו' },
        { id: 'rates', label: 'שהריבית תרד' },
        { id: 'partner', label: 'שיהיה לי בן/בת זוג או שנחליט יחד' },
        { id: 'knowledge', label: 'שאבין את התהליך' },
        { id: 'family', label: 'שינוי במצב המשפחתי' },
        { id: 'job', label: 'שינוי בעבודה או במקום המגורים' },
      ],
    },
    {
      id: 'c_equity_target',
      type: 'single',
      showIf: inC,
      prompt: 'האם יש לך יעד מוגדר להון עצמי, ואת/ה עוקב/ת אחרי ההתקדמות אליו?',
      options: [
        { id: 'target_track', label: 'כן — יש סכום יעד ואני עוקב/ת אחריו באופן קבוע' },
        { id: 'target_no_track', label: 'כן — יש סכום יעד, אבל איני עוקב/ת' },
        { id: 'general', label: 'יש לי יעד באופן כללי, בלי סכום מוגדר' },
        { id: 'none', label: 'אין לי יעד' },
      ],
    },
    {
      id: 'c_barriers',
      type: 'matrix',
      showIf: inC,
      prompt: 'עד כמה הנושאים הבאים מרגישים לך רחוקים או מורכבים?',
      items: [
        { id: 'equity', label: 'לצבור הון עצמי' },
        { id: 'prices', label: 'מחירי הדירות' },
        { id: 'income', label: 'ההכנסה הנדרשת' },
        { id: 'mortgage', label: 'תהליך המשכנתה עצמו' },
        { id: 'tracks', label: 'מסלולים וריביות' },
        { id: 'planning', label: 'תכנון משותף עם בן/בת זוג' },
      ],
      scaleMin: 1,
      scaleMax: 5,
      minLabel: 'קרוב ופשוט',
      maxLabel: 'רחוק ומורכב',
      naLabel: 'לא רלוונטי',
      shuffleItems: true,
    },
    {
      // מטריצת נכון/לא נכון עם עמודת "לא יודע" — שומרת שלושה קודים נפרדים,
      // כפי שכללי הקידוד בשלד דורשים ("אין לאחד לא רלוונטי / לא יודע / לא ענה").
      id: 'c_literacy',
      type: 'matrix',
      showIf: inC,
      prompt: 'לפי מיטב ידיעתך — האם המשפטים הבאים נכונים?',
      items: [
        { id: 'variable', label: 'ההחזר במסלול בריבית משתנה עשוי להשתנות במהלך התקופה' },
        { id: 'longer', label: 'החזר חודשי נמוך יותר עשוי להגדיל את העלות הכוללת של ההלוואה' },
        { id: 'one_bank', label: 'הצעה של בנק אחד אינה בהכרח הטובה ביותר שאפשר לקבל' },
      ],
      scaleMin: 1,
      scaleMax: 2,
      minLabel: 'לא נכון',
      maxLabel: 'נכון',
      naLabel: 'לא יודע/ת',
    },
    {
      id: 'c_small_action',
      type: 'multi',
      showIf: inC,
      prompt: 'איזו פעולה קטנה הייתה מועילה לך כיום?',
      maxSelections: 2,
      shuffleOptions: true,
      options: [
        { id: 'target', label: 'לקבוע יעד הון עצמי ולראות כמה זמן ייקח' },
        { id: 'forecast', label: 'לראות תחזית — מה אוכל לקנות בעוד כמה שנים' },
        { id: 'monthly', label: 'לבנות תוכנית חיסכון חודשית' },
        { id: 'explain', label: 'הסבר פשוט על איך משכנתה עובדת' },
        { id: 'reminder', label: 'תזכורת כשמשהו רלוונטי משתנה' },
        { id: 'none', label: 'אין צורך בשום דבר מאלה', exclusive: true },
      ],
    },
    {
      id: 'c_concept',
      type: 'info',
      showIf: inC,
      title: 'לפני שנמשיך — על מה אנחנו עובדים',
      body: 'אנחנו בוחנים כלי שעוזר להיערך מוקדם: לקבוע יעד הון עצמי, לראות כמה זמן ייקח להגיע אליו ולהבין מה נדרש — בלי צורך להגיש בקשת משכנתה או לדבר עם בנק.\n\nהכלי אינו נותן ייעוץ ואינו מבטיח תוצאה.',
      cta: 'הבנתי, נמשיך',
    },
    {
      id: 'c_commit',
      type: 'single',
      showIf: inC,
      prompt: 'איזו פעולה תהיה מוכן/ה לבצע השבוע?',
      options: [
        { id: 'read', label: 'לקרוא מידע או מדריך' },
        { id: 'target', label: 'להזין יעד הון עצמי' },
        { id: 'monthly', label: 'להגדיר סכום חיסכון חודשי' },
        { id: 'reminder', label: 'להירשם לתזכורת' },
        { id: 'call', label: 'לקבוע שיחה של 20 דקות' },
        { id: 'none', label: 'אף אחת מהפעולות' },
      ],
    },
    {
      id: 'c_deposit',
      type: 'single',
      showIf: inC,
      prompt: 'האם תהיה מוכן/ה להפקיד סכום חודשי קבוע או להפעיל הוראת חיסכון למטרה זו?',
      options: [
        { id: 'already', label: 'כן — אני כבר עושה זאת' },
        { id: 'yes', label: 'כן' },
        { id: 'maybe', label: 'אולי' },
        { id: 'no', label: 'לא' },
      ],
    },

    // ─────────────────────── בלוק 5 · דמוגרפיה (משותפת) ───────────────────────
    // הגיל כבר נשאל ב-s_age ואינו נשאל שוב.
    {
      id: 'd_gender',
      type: 'single',
      prompt: 'כיצד את/ה מגדיר/ה את עצמך?',
      options: [
        { id: 'female', label: 'אישה' },
        { id: 'male', label: 'גבר' },
        { id: 'other', label: 'אחר' },
        { id: 'prefer', label: 'מעדיף/ה לא להשיב' },
      ],
    },
    {
      id: 'd_household',
      type: 'single',
      prompt: 'מה מתאר את משק הבית שלך?',
      options: [
        { id: 'single', label: 'יחיד/ה' },
        { id: 'couple', label: 'זוג ללא ילדים' },
        { id: 'family', label: 'משפחה עם ילדים' },
        { id: 'single_parent', label: 'הורה יחיד/ה' },
        { id: 'with_parents', label: 'גר/ה עם ההורים' },
        { id: 'roommates', label: 'שותפים' },
        { id: 'other', label: 'אחר' },
      ],
    },
    {
      id: 'd_district',
      type: 'single',
      prompt: 'באיזה מחוז את/ה מתגורר/ת?',
      options: [
        { id: 'jerusalem', label: 'ירושלים' },
        { id: 'north', label: 'צפון' },
        { id: 'haifa', label: 'חיפה' },
        { id: 'center', label: 'מרכז' },
        { id: 'tel_aviv', label: 'תל אביב' },
        { id: 'south', label: 'דרום' },
        { id: 'judea_samaria', label: 'יהודה ושומרון' },
        { id: 'abroad', label: 'איני מתגורר/ת בישראל כרגע' },
      ],
    },
    {
      // רב-ברירה במכוון: מטפל ב"גם שכיר וגם עצמאי", ומארח את S8 בלי מסך נוסף.
      id: 'd_employment',
      type: 'multi',
      prompt: 'אילו מהמצבים הבאים מתארים אותך?',
      options: [
        { id: 'employee', label: 'שכיר/ה' },
        { id: 'self_employed', label: 'עצמאי/ת' },
        { id: 'unemployed', label: 'לא עובד/ת כרגע' },
        { id: 'retired', label: 'גמלאי/ת' },
        { id: 'student', label: 'סטודנט/ית' },
        {
          id: 'industry',
          label: 'אני, או בן/בת משפחה מדרגה ראשונה, עובדים בבנק, בגוף אשראי או בייעוץ משכנתאות',
        },
      ],
    },
    {
      id: 'd_income_stability',
      type: 'single',
      prompt: 'עד כמה הכנסת משק הבית משתנה מחודש לחודש?',
      options: [
        { id: 'stable', label: 'קבועה לחלוטין' },
        { id: 'mostly_stable', label: 'משתנה מעט' },
        { id: 'somewhat', label: 'משתנה במידה בינונית' },
        { id: 'variable', label: 'משתנה הרבה' },
        { id: 'very_variable', label: 'משתנה מאוד — קשה לחזות' },
      ],
    },
    {
      id: 'd_income',
      type: 'single',
      prompt: 'מהי הכנסת משק הבית נטו בחודש רגיל?',
      options: [
        { id: 'upto10', label: 'עד 10,000 ש"ח' },
        { id: 'r10_15', label: '10,001–15,000 ש"ח' },
        { id: 'r15_20', label: '15,001–20,000 ש"ח' },
        { id: 'r20_30', label: '20,001–30,000 ש"ח' },
        { id: 'r30_40', label: '30,001–40,000 ש"ח' },
        { id: 'over40', label: 'מעל 40,000 ש"ח' },
        { id: 'prefer', label: 'מעדיף/ה לא להשיב' },
      ],
    },
    {
      id: 'd_assets',
      type: 'single',
      prompt: 'כמה דירות נמצאות בבעלותך או בבעלות משק הבית?',
      options: [
        { id: 'none', label: 'אף אחת' },
        { id: 'one', label: 'אחת' },
        { id: 'two_plus', label: 'שתיים או יותר' },
        { id: 'prefer', label: 'מעדיף/ה לא להשיב' },
      ],
    },

    // ─────────────────────── בלוק 6 · סיום ומחויבות ───────────────────────
    {
      // עקרון הפרטיות בשלד: "פרטי קשר למחקר המשך יישמרו בנפרד מן התשובות",
      // ולכן השאלון עצמו לא אוסף אותם.
      id: 'end_followup',
      type: 'single',
      prompt: 'האם תרצה/י להשתתף בבדיקת המשך קצרה?',
      // ⚠ הניסוח לא מבטיח טופס שאינו קיים (docs/wording-v1.md, פתוח #5).
      // כשייווצר טופס פרטי קשר חיצוני — להוסיף קישור אליו ל-end_complete
      // ולעדכן את הניסוח כאן בהתאם.
      help: 'לא נבקש כאן פרטי קשר. אם תסמן/י "כן", נפנה אליך דרך אותו ערוץ שבו הגיע אליך השאלון.',
      options: [
        { id: 'yes', label: 'כן, אשמח' },
        { id: 'no', label: 'לא, תודה' },
      ],
    },
    {
      id: 'end_complete',
      type: 'end',
      variant: 'complete',
      title: 'תודה רבה!',
      body: 'התשובות נשמרו. תרומתך עוזרת לנו להבין מה באמת חסר לאנשים בתהליך המשכנתה.',
    },
    {
      id: 'end_screenout',
      type: 'end',
      variant: 'screenout',
      title: 'תודה על ההתעניינות',
      body: 'השאלון אינו מתאים למצבך הנוכחי, ולכן נסיים כאן. תודה רבה על הזמן!',
    },
  ],
};
